// Source label (normalised) -> our funds.id. Full map: every seeded MMF fund
// resolves, so the Serrari, press and industry adapters all map cleanly.
// Official names from CMA CIS Q1-2026; ids match the seeded funds table.
//
// KES/USD share manager tokens ("cytonn"); index.ts merges {...KES, ...USD}
// so USD wins shared tokens — fine for USD sources. The Serrari /ke/mmf page is
// KES-only, so its adapter reads SERRARI_KES_MMF_MAP (casual -> official name)
// and emits the official name, which KES_MMF_NAME_MAP resolves to a KES id.

// KES MMFs: manager tokens + official names -> id
export const KES_MMF_NAME_MAP: Record<string, string> = {
  // press/sheet labels that drop the DB name suffix (KES / Allianz / (KES))
  "sanlam money market fund": "sanlam-mmf-kes",
  "kuza money market fund": "kuza-mmf-kes",
  "ncba money market fund": "ncba-mmf-kes",
  "sanlamallianz money market fund": "sanlam-mmf-kes",
  "sanlam": "sanlam-mmf-kes",
  "sanlam allianz": "sanlam-mmf-kes",
  "sanlamallianz": "sanlam-mmf-kes",
  "cic money market fund": "cic-mmf-kes",
  "cic": "cic-mmf-kes",
  "britam money market fund": "britam-mmf-kes",
  "britam": "britam-mmf-kes",
  "ncba money market (kes) fund": "ncba-mmf-kes",
  "ncba": "ncba-mmf-kes",
  "old mutual money market fund": "oldmutual-mmf-kes",
  "old mutual": "oldmutual-mmf-kes",
  "oldmutual": "oldmutual-mmf-kes",
  "absa shilling money market fund": "absa-mmf-kes",
  "absa": "absa-mmf-kes",
  "absa shilling": "absa-mmf-kes",
  "jubilee money market fund kes": "jubilee-mmf-kes",
  "jubilee": "jubilee-mmf-kes",
  "co-op money market fund": "coop-mmf-kes",
  "co-op": "coop-mmf-kes",
  "coop": "coop-mmf-kes",
  "co op": "coop-mmf-kes",
  "icea lion money market fund": "icealion-mmf-kes",
  "icea lion": "icealion-mmf-kes",
  "icea": "icealion-mmf-kes",
  "icealion": "icealion-mmf-kes",
  "icea-lion": "icealion-mmf-kes",
  "kcb money market fund kes": "kcb-mmf-kes",
  "kcb": "kcb-mmf-kes",
  "etica money market fund": "etica-mmf-kes",
  "etica": "etica-mmf-kes",
  "ziidi money market fund": "ziidi-money-market-fund-mmf-kes",
  "ziidi": "ziidi-money-market-fund-mmf-kes",
  "safaricom": "ziidi-money-market-fund-mmf-kes",
  "m-pesa": "ziidi-money-market-fund-mmf-kes",
  "mpesa": "ziidi-money-market-fund-mmf-kes",
  "madison money market fund": "madison-mmf-kes",
  "madison": "madison-mmf-kes",
  "nabo kes money market fund": "nabo-africa-funds-mmf-kes",
  "nabo": "nabo-africa-funds-mmf-kes--2",
  "nabo africa": "nabo-africa-funds-mmf-kes--2",
  "nabo kes": "nabo-africa-funds-mmf-kes",
  "nabo africa money market fund": "nabo-africa-funds-mmf-kes--2",
  "arvocap money market fund": "arvocap-mmf-kes",
  "arvocap": "arvocap-mmf-kes",
  "avrocap": "arvocap-mmf-kes",
  "dry associates money market fund kes": "dry-associates-mmf-kes",
  "dry associates": "dry-associates-mmf-kes",
  "dryassociates": "dry-associates-mmf-kes",
  "dry": "dry-associates-mmf-kes",
  "stanbic money market fund": "stanbic-mmf-kes",
  "stanbic": "stanbic-mmf-kes",
  "cpf money market fund": "cpf-mmf-kes",
  "cpf": "cpf-mmf-kes",
  "lofty corban money market fund": "lofty-corban-mmf-kes",
  "lofty corban": "lofty-corban-mmf-kes",
  "loftycorban": "lofty-corban-mmf-kes",
  "lofty": "lofty-corban-mmf-kes",
  "genafrica money market fund": "genafrica-mmf-kes",
  "genafrica": "genafrica-mmf-kes",
  "gen africa": "genafrica-mmf-kes",
  "kuza money market fund kes": "kuza-mmf-kes",
  "kuza": "kuza-mmf-kes",
  "mayfair money market fund": "mayfair-mmf-kes",
  "mayfair": "mayfair-mmf-kes",
  "apollo money market fund": "apollo-mmf-kes",
  "apollo": "apollo-mmf-kes",
  // Apollo trades under the "APA" brand on the Serrari board.
  "apa": "apollo-mmf-kes",
  "cytonn money market fund": "cytonn-mmf-kes",
  "cytonn": "cytonn-mmf-kes",
  "mali money market fund": "mali-money-market-fund-mmf-kes",
  "mali": "mali-money-market-fund-mmf-kes",
  "enwealth money market fund": "enwealth-mmf-kes",
  "enwealth": "enwealth-mmf-kes",
  "gcib money market fund": "gulfcap-mmf-kes",
  "gulfcap": "gulfcap-mmf-kes",
  "gcib": "gulfcap-mmf-kes",
  "genghis capital": "gulfcap-mmf-kes",
  "orient kasha money market fund": "orient-mmf-kes",
  "orient kasha": "orient-mmf-kes",
  "orient": "orient-mmf-kes",
  "kasha": "orient-mmf-kes",
  "genghis money market fund": "genghis-mmf-kes",
  "genghis": "genghis-mmf-kes",
  "gencap hela money market fund": "genghis-mmf-kes-gencap-hela",
  "faulu money market fund": "faulu-mmf-kes",
  "faulu": "faulu-mmf-kes",
  "taifa money market fund kes": "taifa-mmf-kes",
  "taifa": "taifa-mmf-kes",
  "ziidi shariah money market fund": "ziidi-shariah-money-market-fund-mmf-kes",
  "ziidi shariah": "ziidi-shariah-money-market-fund-mmf-kes",
  "eib money market fund": "equity-investment-bank-mmf-kes",
  "equity": "equity-investment-bank-mmf-kes",
  "eib": "equity-investment-bank-mmf-kes",
  "equity investment bank": "equity-investment-bank-mmf-kes",
  // African Alliance — created in-app as "AA Kenya Money Market Fund".
  // VERIFY this id matches the fund (admin URL /admin/funds/<id>) before you
  // push: a wrong id FK-errors the whole run. Expected slug shown below.
  "aa kenya money market fund": "aa-kenya-money-market-fund",
  "african alliance money market fund": "aa-kenya-money-market-fund",
  "african alliance": "aa-kenya-money-market-fund",
  "aa kenya": "aa-kenya-money-market-fund",
  // Zimele MMF (surfaces via press-mmf). Add its id once confirmed — leaving it
  // unmapped is harmless, but a wrong id FK-errors the run, so do NOT guess:
  // "zimele money market fund": "<zimele-mmf-id>",
  // "zimele": "<zimele-mmf-id>",
  "xeno kenya money market fund": "xeno-mmf-kes",
  "xeno": "xeno-mmf-kes",
  "amana money market fund": "amana-mmf-kes",
  "amana": "amana-mmf-kes",
};

// USD MMFs: manager tokens + official names -> id
export const USD_MMF_NAME_MAP: Record<string, string> = {
  "cic dollar money market fund": "cic-mmf-usd",
  "cic": "cic-mmf-usd",
  "britam usd money market fund": "britam-mmf-usd",
  "britam": "britam-mmf-usd",
  "ncba money market (usd) fund": "ncba-mmf-usd",
  "ncba": "ncba-mmf-usd",
  "old mutual dollar money market fund": "old-mutual-mmf-usd",
  "old mutual": "old-mutual-mmf-usd",
  "absa dollar money market fund": "absa-mmf-usd",
  "absa": "absa-mmf-usd",
  "jubilee money market fund usd": "jubilee-mmf-usd",
  "jubilee": "jubilee-mmf-usd",
  "kcb money market fund usd": "kcb-mmf-usd",
  "kcb": "kcb-mmf-usd",
  "etica money market fund -usd": "etica-mmf-usd",
  "etica": "etica-mmf-usd",
  "dry associates money market fund usd": "dry-associates-mmf-usd",
  "dry associates": "dry-associates-mmf-usd",
  "dry": "dry-associates-mmf-usd",
  "cpf usd money market fund": "cpf-mmf-usd",
  "cpf": "cpf-mmf-usd",
  "lofty corban money market fund usd": "lofty-corban-mmf-usd",
  "kuza money market fund usd": "kuza-mmf-usd",
  "kuza": "kuza-mmf-usd",
  "cytonn money market fund usd": "cytonn-mmf-usd",
  "cytonn": "cytonn-mmf-usd",
  "enwealth dollar money market fund": "enwealth-mmf-usd",
  "enwealth": "enwealth-mmf-usd",
  "orient dollar money market fund": "orient-mmf-usd",
  "orient": "orient-mmf-usd",
  "taifa money market fund usd": "taifa-mmf-usd",
  "taifa": "taifa-mmf-usd",
};

// Serrari casual label -> official KES name
export const SERRARI_KES_MMF_MAP: Record<string, string> = {
  "sanlam": "SanlamAllianz Money Market Fund",
  "sanlam allianz": "SanlamAllianz Money Market Fund",
  "sanlamallianz": "SanlamAllianz Money Market Fund",
  "cic": "CIC Money Market Fund",
  "britam": "Britam Money Market Fund",
  "ncba": "NCBA Money Market (KES) Fund",
  "old mutual": "Old Mutual Money Market Fund",
  "oldmutual": "Old Mutual Money Market Fund",
  "absa": "ABSA Shilling Money Market Fund",
  "absa shilling": "ABSA Shilling Money Market Fund",
  "jubilee": "Jubilee Money Market Fund KES",
  "co-op": "Co-op Money Market Fund",
  "coop": "Co-op Money Market Fund",
  "co op": "Co-op Money Market Fund",
  "icea lion": "ICEA LION Money Market Fund",
  "icea": "ICEA LION Money Market Fund",
  "icealion": "ICEA LION Money Market Fund",
  "icea-lion": "ICEA LION Money Market Fund",
  "kcb": "KCB Money Market Fund KES",
  "etica": "Etica Money Market Fund",
  "ziidi": "Ziidi Money Market Fund",
  "safaricom": "Ziidi Money Market Fund",
  "m-pesa": "Ziidi Money Market Fund",
  "mpesa": "Ziidi Money Market Fund",
  "madison": "Madison Money Market Fund",
  "nabo": "Nabo Africa Money Market Fund",
  "nabo africa": "Nabo Africa Money Market Fund",
  "nabo kes": "Nabo KES Money Market Fund",
  "arvocap": "Arvocap Money Market Fund",
  "avrocap": "Arvocap Money Market Fund",
  "dry associates": "Dry Associates Money Market Fund KES",
  "dryassociates": "Dry Associates Money Market Fund KES",
  "dry": "Dry Associates Money Market Fund KES",
  "stanbic": "Stanbic Money Market Fund",
  "cpf": "CPF Money Market Fund",
  "lofty corban": "Lofty Corban Money Market Fund",
  "loftycorban": "Lofty Corban Money Market Fund",
  "lofty": "Lofty Corban Money Market Fund",
  "genafrica": "GenAfrica Money Market Fund",
  "gen africa": "GenAfrica Money Market Fund",
  "kuza": "Kuza Money Market Fund KES",
  "mayfair": "Mayfair Money Market Fund",
  "apollo": "Apollo Money Market Fund",
  "apa": "Apollo Money Market Fund",
  "cytonn": "Cytonn Money Market Fund",
  "mali": "Mali Money Market Fund",
  "enwealth": "Enwealth Money Market Fund",
  "gulfcap": "GCIB Money Market Fund",
  "gcib": "GCIB Money Market Fund",
  "genghis capital": "GCIB Money Market Fund",
  "orient kasha": "Orient Kasha Money Market Fund",
  "orient": "Orient Kasha Money Market Fund",
  "kasha": "Orient Kasha Money Market Fund",
  "genghis": "Genghis Money Market Fund",
  "faulu": "Faulu Money Market Fund",
  "taifa": "Taifa Money Market Fund KES",
  "ziidi shariah": "Ziidi Shariah Money Market Fund",
  "equity": "EIB Money Market Fund",
  "eib": "EIB Money Market Fund",
  "equity investment bank": "EIB Money Market Fund",
  "african alliance": "AA Kenya Money Market Fund",
  "aa kenya": "AA Kenya Money Market Fund",
  "xeno": "XENO Kenya Money Market Fund",
  "amana": "Amana Money Market Fund",
};

export function normalize(name: string): string {
  return name.trim().toLowerCase().replace(/\s+/g, " ");
}
